pipeline {
  environment {
    registry = "matancarmeli7/security_camera-2"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('template the kubernetes creation yml ') {
      steps{
        ansiblePlaybook(
          playbook: 'Services/SecurityCamera/scenario2/ansible_playbooks/pre-kubeDeploy.yml',
          extraVars: [
              buildId: '$BUILD_NUMBER',
              jobName: '$JOB_NAME',
	      registry: '$registry'
          ])
      }
    }
    stage('deploy the application on kubernetes cluster') {
        steps{
            sh "kubectl apply -f /var/lib/jenkins/workspace/$JOB_NAME/Services/SecurityCamera/scenario2/kubernetes_deploy/full-deployment.yml"
        }
    }
  }
}
