apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: {{buildId}}
  labels:
    app: alarm
  name: alarm
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alarm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alarm
    spec:
    nodeSelector:
      kubernetes.io/hostname: raspberrypi3
      containers:
      - image: {{registry}}:{{buildId}}
        env:
        - name: HOSTIP
          value: "172.20.10.2"
        imagePullPolicy: IfNotPresent
        name: alarm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          privileged: true 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alarm
  name: alarm
  namespace: default
spec:
  ports:
  - name: alarm
    nodePort: 31705
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: alarm
  type: NodePort
