- hosts: localhost
  gather_facts: false
  tasks:
  - name: template the kubernetes creation yml
    template:
      src: "/var/lib/jenkins/workspace/{{jobName}}/Services/SecurityCamera/scenario2/kubernetes_deploy/full-deployment.yml"
      dest: "/var/lib/jenkins/workspace/{{jobName}}/Services/SecurityCamera/scenario2/kubernetes_deploy/full-deployment.yml"
      force: yes
